# documentation for tasks can be found @ https://github.com/techdecaf/tasks
options:
  log: true

variables:
  CI_PROJECT_NAME: '{{ReadFile `.cgen.yaml` | YQ `answers.Name`}}'
  CI_COMMIT_TAG: '{{EXEC `git describe --tags --always --dirty --abbrev=0`}}'
  CI_COMMIT_REF_NAME: '{{EXEC `git rev-parse --abbrev-ref HEAD`}}'
  CI_COMMIT_SHA: '{{EXEC `git rev-parse HEAD`}}'
  BUILD_DIR: 'build'

tasks:
  default:
    description: is the task that runs when no tasks have been specified.
    commands: [tasks list]

  symlink:
    description: install current generator
    commands:
      - mkdir -p {{.HOME}}/.cgen/generators
      - ln -s {{PWD}} {{.HOME}}/.cgen/generators/{{.CI_PROJECT_NAME}}

  build:
    description: build current project
    pre: [clean]
    variables:
      Name: '{{uuidv4}}'
      DESCRIPTION: end-to-end tests
      AUTHOR: your.email@domain.com
      GIT_BASE_URL: https://github.com/techdecaf
    commands: ['cgen -p {{.BUILD_DIR}} -t {{.CI_PROJECT_NAME}}']

  upgrade-dependencies:
    description: upgrade dependencies from generated template directory
    commands:
      - jq -n 'input | .dependencies = input.dependencies' template/package.json.tmpl {{.BUILD_DIR}}/package.json > package.json.tmpl
      - mv package.json.tmpl template/package.json.tmpl
      - jq -n 'input | .devDependencies = input.devDependencies' template/package.json.tmpl {{.BUILD_DIR}}/package.json > package.json.tmpl
      - mv package.json.tmpl template/package.json.tmpl
      - 'cp {{.BUILD_DIR}}/yarn.lock template/yarn.lock.tmpl'

  clean:
    description: remove files created as part of the build step.
    commands: ['rm -rf {{.BUILD_DIR}}']

  test:
    description: generate a new template and run a full test suite
    dir: build
    pre: [build]
    commands: [tasks run login dependencies coverage audit e2e]

  release:
    description: bump version and release
    commands: ['cgen bump -l patch --push']
